// Builds docs/qa/test-cases.md from the test titles, so the documented cases cannot drift from the
// automated ones. Run `npm run docs:test-cases` to regenerate; tests/unit/qa-docs.spec.ts checks it is current.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const REQUIREMENTS: Record<string, string> = {
  R1: "Content integrity: one bilingual Content Source, validated, with no missing translations",
  R2: "Locale: English by default, ?lang deep link, toggle, persistence, safe fallback",
  R3: "Theme: OS preference first, dark fallback, toggle, persistence, no flash, AA contrast",
  R4: "Sections: QA-relevant entries visible, Core Skills first, certifications, contact, responsive",
  R5: "Modals: More (experience, education) and Dev Projects, keyboard accessible, localized",
  R6: "Accessibility: WCAG 2.1 AA in every Theme and Locale, with and without open modals",
  R7: "Visual consistency across Theme, Locale and viewport",
  R8: "Privacy: no birthday or phone number on the web page; phone only in the PDFs",
  R9: "CV PDFs: English and Portuguese downloads that match the site",
  R10: "Transparency: the testing section is accurate and linked to evidence",
  R11: "Performance and SEO budgets",
  R12: "Links: no broken internal or external links",
  R13: "Delivery: deploy only when the whole Test Suite passes",
};

// Area prefix (the middle part of TC-<AREA>-<n>) to the requirements it verifies.
export const AREAS: Record<string, { name: string; requirements: string[] }> = {
  SKEL: { name: "Walking skeleton", requirements: ["R13"] },
  CON: { name: "Content Source", requirements: ["R1"] },
  LOC: { name: "Locale", requirements: ["R2"] },
  THM: { name: "Theme", requirements: ["R3"] },
  SEC: { name: "Page sections", requirements: ["R4"] },
  MOD: { name: "Modals", requirements: ["R5"] },
  A11Y: { name: "Accessibility", requirements: ["R6"] },
  VIS: { name: "Visual regression", requirements: ["R7", "R13"] },
  PDF: { name: "CV PDFs", requirements: ["R9"] },
  TST: { name: "Testing section", requirements: ["R10"] },
  LNK: { name: "Links", requirements: ["R12"] },
  NGT: { name: "Nightly checks", requirements: ["R11", "R12", "R13"] },
  DOC: { name: "QA documentation", requirements: ["R10"] },
};

// Cases that protect a different requirement than the rest of their area.
const OVERRIDES: Record<string, string[]> = {
  "TC-CON-06": ["R8"],
  "TC-CON-07": ["R8"],
  "TC-SEC-08": ["R8"],
  "TC-SEC-U7": ["R8"],
  "TC-PDF-06": ["R8"],
  "TC-PDF-U2": ["R8", "R9"],
  "TC-A11Y-U1": ["R3", "R6"],
};

const requirementsOf = (c: { id: string; area: string }): string[] =>
  OVERRIDES[c.id] ?? AREAS[c.area]?.requirements ?? [];

interface Case {
  id: string;
  title: string;
  layer: "Unit" | "E2E" | "Visual";
  area: string;
}

const LAYERS: [string, Case["layer"]][] = [
  ["tests/unit", "Unit"],
  ["tests/e2e", "E2E"],
  ["tests/visual", "Visual"],
];

function specFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true })
    .flatMap((entry) => (entry.isDirectory() ? specFiles(join(dir, entry.name)) : [join(dir, entry.name)]))
    .filter((file) => file.endsWith(".spec.ts"))
    .sort();
}

export function collectCases(root = "."): Case[] {
  const byId = new Map<string, Case>();
  for (const [dir, layer] of LAYERS) {
    for (const file of specFiles(join(root, dir))) {
      const source = readFileSync(file, "utf8");
      // Titles are the first string argument of test(...) / it(...) / it.each(...)(...).
      for (const match of source.matchAll(/(?:test|it)(?:\.each\([^)]*\))?\(\s*[`"'](TC-([A-Z0-9]+)-([A-Z]?\d+))\s+([^`"']*)[`"']/g)) {
        const [, id, area, , rawTitle] = match;
        if (!byId.has(id)) {
          const title = rawTitle.replace(/\$\{[^}]*\}/g, "…").replace(/%[sd]/g, "…").trim();
          byId.set(id, { id, title, layer, area });
        }
      }
    }
  }
  return [...byId.values()].sort((a, b) => a.id.localeCompare(b.id, "en", { numeric: true }));
}

export function buildTestCasesDoc(root = "."): string {
  const cases = collectCases(root);
  const rows = cases
    .map((c) => {
      const requirements = requirementsOf(c).join(", ") || "?";
      return `| ${c.id} | ${c.layer} | ${c.title.replace(/\|/g, "\\|")} | ${requirements} |`;
    })
    .join("\n");

  const requirementRows = Object.entries(REQUIREMENTS)
    .map(([id, text]) => {
      const covering = cases.filter((c) => requirementsOf(c).includes(id)).length;
      return `| ${id} | ${text} | ${covering} |`;
    })
    .join("\n");

  return `# Test cases

> Generated by \`npm run docs:test-cases\` from the titles of the automated tests. Do not edit by hand:
> a unit test fails when this file is out of date. Test-case IDs appear in the test titles, so a failing
> check in CI can be traced back to this table and to the requirement it protects.

${cases.length} test cases.

## Requirements and coverage

| Requirement | Statement | Test cases |
| --- | --- | --- |
${requirementRows}

## Cases

Cases that run once per Theme, Locale or dialog (for example the accessibility matrix) share one ID.

| ID | Layer | Title | Requirements |
| --- | --- | --- | --- |
${rows}
`;
}

if (process.argv[1]?.endsWith("test-cases.ts") && process.argv.includes("--write")) {
  writeFileSync("docs/qa/test-cases.md", buildTestCasesDoc());
  console.log("wrote docs/qa/test-cases.md");
}
